version: '3.8'

services:
  mysql-local:
    image: arm64v8/mysql:oracle
    container_name: mysql-local
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      # # This variable is optional and allows you to specify the name of a database to be created on image startup. If a user/password was supplied (see below) then that user will be granted superuser access (corresponding to GRANT ALL) to this database.
      # MYSQL_DATABASE: 'test'
      # # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'user'
      # # You can use whatever password you like
      # MYSQL_PASSWORD: 'password'
      # Password for root access
      # Username: root
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ~/data/mysql:/var/lib/mysql

version: '3.8'

services:
  rabbitmq-local:
    image: rabbitmq:3.10-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/data/rabbitmq:/var